---
- name: Install Docker and Start Container
  hosts: docker_hosts
  become: yes
  
  tasks:
    - name: Install Docker on Debian
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: ansible_distribution == 'Debian'

    - name: Install Docker on CentOS
      ansible.builtin.yum:
        name: docker-ce
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker image file
      ansible.builtin.copy:
        src: /path/to/your/docker_image.tar.gz
        dest: /tmp/docker_image.tar.gz

    - name: Load Docker image
      ansible.builtin.command: docker load -i /tmp/docker_image.tar.gz

    - name: Start Docker container
      ansible.builtin.command: docker run -d --name my_container -p 80:80 your_image_name:tag
